version: "3"
services:
  dbcars:
    image: postgres
    container_name: db_cars
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cars
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - dbcars
    depends_on:
      - dbcars
volumes:
  pgdata:
    driver: local
